"use client";
import {useMemo,useState} from "react";
type R={id:number;created_at:string;source:string|null;answers:Record<string,string|string[]>};
const labels:Record<string,string>={business:"Business",outlets:"Locations",role:"Role",pain:"Main problems",channels:"Customer channels",repetitive:"Repeated questions",missed:"Delayed/missed requests",lost:"Lost enquiries",automate:"Tasks to remove",systems:"Current tools",value_score:"Value of solving it",price:"Reasonable monthly price",biggest:"Biggest problem",contact:"Contact"};
function vals(rows:R[],key:string){const m=new Map<string,number>();rows.forEach(r=>{const v=r.answers?.[key],a=Array.isArray(v)?v:v?[v]:[];a.forEach(x=>m.set(x,(m.get(x)||0)+1))});return [...m.entries()].sort((a,b)=>b[1]-a[1])}
const pct=(n:number,t:number)=>t?Math.round(n*100/t):0;
export default function Dashboard(){
const[pw,setPw]=useState(""),[auth,setAuth]=useState(""),[rows,setRows]=useState<R[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
async function load(){setLoading(true);setError("");const token="Basic "+btoa("admin:"+pw);const r=await fetch("/api/admin/responses",{headers:{Authorization:token},cache:"no-store"});if(!r.ok){setError(r.status===401?"Wrong password.":"Could not load responses.");setLoading(false);return}const d=await r.json();setAuth(token);setRows(d.responses||[]);setLoading(false)}
const m=useMemo(()=>{const t=rows.length;return{t,lost:rows.filter(r=>["Sometimes","Often"].includes(String(r.answers?.lost))).length,rep:rows.filter(r=>["A lot","A significant amount"].includes(String(r.answers?.repetitive))).length,high:rows.filter(r=>["Very valuable","Extremely valuable"].includes(String(r.answers?.value_score))).length,pay:rows.filter(r=>!["I wouldn’t pay for it","It depends on the results it delivers"].includes(String(r.answers?.price))).length}},[rows]);
async function download(){const r=await fetch("/api/admin/export",{headers:{Authorization:auth}});if(!r.ok)return;const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="hospitality-survey-responses.csv";a.click();URL.revokeObjectURL(u)}
if(!auth)return <main className="admin-shell"><section className="admin-card"><div className="eyebrow">Private research</div><h1>Survey dashboard</h1><p>Enter the admin password to view responses.</p><input className="admin-input" type="password" value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Admin password"/><button className="admin-button" onClick={load} disabled={loading}>{loading?"Checking…":"Open dashboard"}</button>{error&&<p className="admin-error">{error}</p>}</section></main>;
const sections=["pain","channels","missed","automate","systems","business","role","repetitive","lost","value_score","price"];
return <main className="admin-shell"><div className="admin-head"><div><div className="eyebrow">Private research</div><h1>Hospitality pulse</h1><p>{m.t} response{m.t===1?"":"s"} collected</p></div><div className="admin-actions"><button className="admin-button secondary" onClick={load}>Refresh</button><button className="admin-button" onClick={download}>Export CSV</button></div></div>
<section className="metric-grid">{[["Responses",m.t,""],["Lost enquiries",pct(m.lost,m.t)+"%","Sometimes / often"],["Repetitive work",pct(m.rep,m.t)+"%","A lot / significant"],["High value",pct(m.high,m.t)+"%","Very / extremely valuable"],["Paying signal",pct(m.pay,m.t)+"%","Selected a price band"]].map(([a,b,c])=><div className="metric-card" key={String(a)}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</section>
<section className="insight-grid">{sections.map(k=><div className="insight-card" key={k}><h2>{labels[k]}</h2>{vals(rows,k).slice(0,8).map(([n,c])=><div className="bar-row" key={n}><div className="bar-label"><span>{n}</span><b>{c} · {pct(c,m.t)}%</b></div><div className="bar"><i style={{width:pct(c,m.t)+"%"}}/></div>)}</div>)}</section>
<section className="responses-card"><div className="section-head"><h2>Individual responses</h2><span>Newest first</span></div>{rows.map(r=><details key={r.id}><summary><b>#{r.id}</b> · {new Date(r.created_at).toLocaleString()} · {String(r.answers.business||"Unknown business")}</summary><div className="response-detail">{Object.entries(r.answers).map(([k,v])=><div key={k}><b>{labels[k]||k}</b><span>{Array.isArray(v)?v.join(", "):v}</span></div>)}</div></details>)}</section></main>}